FROM node:22.18.0-slim AS deps
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci

FROM node:22.18.0-slim AS builder
WORKDIR /usr/src/app
COPY  --from=deps /usr/src/app/package*.json ./
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . ./
RUN npm run build

FROM node:22.18.0-slim AS runner
ENV NODE_ENV=production
WORKDIR /usr/src/app
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
COPY --from=builder /usr/src/app/public ./public
COPY --from=builder --chown=nextjs:nodejs /usr/src/app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /usr/src/app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
